### ISSUE TITLE
Help Install 

### ISSUE THREAD

**Issue by AndreJaarconsult** [sql-bi/Contoso-Data-Generator#2]
Hi guys!
I've installed dotnet3.1 and 7zip and just exec quickrun with Powershell.

When executing the QuickRun / GenerateDatabases
complaining about:
Contoso-Data-Generator-main\Scripts\..\DatabaseGenerator\bin\Release\netcoreapp3.1\DatabaseGenerator.exe
i don't have any bin folder

![image](https://user-images.githubusercontent.com/59178334/172189502-f13f24b5-bfb9-425f-a8cb-64d817d71d89.png)
------------------------------------------------------
![image](https://user-images.githubusercontent.com/59178334/172190207-1aff5556-1acc-40bd-a137-38b78e0a03c8.png)

**Comment by SergioMurru** [comment]
Hi, if you cloned the project, then you would have to compile the DatabaseGenerator project for the Release configuration. 

Otherwise you can download the whole project already compiled 
Contoso-Data-Generator-exe-1.0.0.zip  from the latest release page https://github.com/sql-bi/Contoso-Data-Generator/releases/tag/v1.0.0

**Comment by AndreJaarconsult** [comment]
It Worked, thanks!
Now working on creating the database 
BRegards
